<?php

return [
  'SITE_NAME' => 'Eglee\'s Gourmet',
  'SITE_CODE_NAME' => 'eglees-gourmet',
  'STORE_ID' => '1',
  'SITE_URL' => 'http://template1.test/',
  'SITE_ADMIN_URL' => 'http://template1.test/admin/',
  'SUPPORT_EMAIL' => 'lacocinadeeglee@gmail.com',
  // 'API_URL' => 'http://mystorepanel.test/api',
  'API_URL' => 'https://mystorepanel.com/api',
  'VERSION' => '1.0.0',
  'LOCAL_ENV' => true,
  'META_KEYWORDS' => 'eglee, gourmet, gourmet food, gourmet restaurant, gourmet delivery, arepas, empanadas, comida venezolana, comida latina, comida venezolana en chicago',
  'META_DESCRIPTION' => 'Comida Venezolana en Chicago, hecha en casa y con el sabor de la abuela.',
  'ORDER_NOW' => 'ORDENA AHORA',
  'TEXTO_PONTE_EN_CONTACTO' => 'PONTE EN CONTACTO',
  'TEXT_WELCOME' => '"Deléitate con el auténtico sabor de Venezuela<br />en cada bocado"',
  'TEXT_ESPECIALIDAD' => 'NUESTRA ESPECIALIDAD',
  'TITLE_EMPANADAS' => 'Empanadas',
  'DESCRIPTION_EMPANADAS' => 'La masa más crujiente con los sabores únicos de nuestra tierra.',
  'TEXTO_AREPAS' => 'AREPAS',
  'DESCRIPTION_AREPAS' => 'La que nunca puede faltar en las mesas de nuestra gastronomía.',
  'TITLE_ALMUERZOS' => 'Almuerzos',
  'DESCRIPTION_ALMUERZOS' => 'Degusta de los platos más auténticos con la saz&oacute;n de la se&ntilde;ora de la casa.',
  'TEXTO_SUBSCRIBE' => "SUSCRÍBETE",
  'TEXTO_SUBSCRIBE_ME' => "SUSCRIBIRME",
  'TEXTO_SUBSCRIBE_PARR' => "Únete a nuestra comunidad de amantes del sabor auténtico de Eglee's Gourmet, para recibir actualizaciones de nuestras promos y ofertas.",
  'TEXTO_EMAIL' => "Email",
  'TEXTO_TELF' => "Teléfono",
  'TEXTO_SU_EMAIL' => "Su Email",
  'TEXTO_COMBO' => 'COMBO',
  'PARRAFO_AREPAS' => 'Estas arepas se las traen, con los mejores rellenos, tu paladar nunca será el mismo luego de probarlas.',
  'TXT_ORDER_NOW' => 'ORDENA AHORA',
  'BTN_SEND' => 'ENVIAR',
  'TXT_YOUR_MSG' => 'Your Message',
  'TXT_YOUR_NAME' => 'Your Name',
  'TXT_YOUR_EMAIL' => 'Your Email Address',
];
